### ISSUE TITLE
Position the colorpicker

### ISSUE THREAD

**Issue by apertureless** [apertureless/colourhunt#5]
The color picker should be positioned absolute near the color palette field.

**Comment by simonstaton** [comment]
I gotcha on this

**Comment by simonstaton** [comment]
Here you go https://github.com/apertureless/colourhunt/pull/7

**Comment by simonstaton** [comment]
@apertureless do you need anymore doing to this?

**Comment by apertureless** [comment]
Sorry for the delay. I was pretty busy! Thanks for the pr!
